# Homebrew formula for farwatch CLI
#
# Install: brew install yipjunkai/farwatch/farwatch
#
# Maintenance:
# - This file is auto-regenerated by CI (.github/workflows/release.yml)
#   on every tag push. Version and SHA256 hashes are computed automatically.
# - The install script (install.sh) is the other install path and requires
#   no updates on release.
# - Do not edit manually — changes will be overwritten by the next release.

class Farwatch < Formula
  desc "Mirror local AI terminal sessions to remote clients with E2E encryption"
  homepage "https://github.com/yipjunkai/farwatch"
  license any_of: ["MIT", "Apache-2.0"]
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/yipjunkai/farwatch/releases/download/v0.1.0/farwatch-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "b98b184207ec42f80848ee2177d67032a1b12d6c622a3e3c5e6309edf701e142"
    end

    on_arm do
      url "https://github.com/yipjunkai/farwatch/releases/download/v0.1.0/farwatch-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "f168c388accf8b91fcaebec81bfac9d6d4315a1a137e1acab96f3ddee7001419"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yipjunkai/farwatch/releases/download/v0.1.0/farwatch-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a29a78c213b33cc603d6b27d2f800814a50b585e597f20a18f58d6d5b1776e7c"
    end

    on_arm do
      url "https://github.com/yipjunkai/farwatch/releases/download/v0.1.0/farwatch-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1470150cde96796b5ca8fd072bf990621bf39e8eaba73fec6caa74feea50b2de"
    end
  end

  def install
    bin.install "farwatch"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/farwatch --version")
  end
end
