# Homebrew formula for terminal-relay CLI
#
# Install: brew install yipjunkai/terminal-relay/terminal-relay
#
# Maintenance:
# - This file is auto-regenerated by CI (.github/workflows/release.yml)
#   on every tag push. Version and SHA256 hashes are computed automatically.
# - The install script (install.sh) is the other install path and requires
#   no updates on release.
# - Do not edit manually — changes will be overwritten by the next release.

class TerminalRelay < Formula
  desc "Mirror local AI terminal sessions to remote clients with E2E encryption"
  homepage "https://github.com/yipjunkai/terminal-relay"
  license any_of: ["MIT", "Apache-2.0"]
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/yipjunkai/terminal-relay/releases/download/v0.1.0/terminal-relay-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "60934797714e512396ccc9421822f3e4bb371fdff7596ce0bfe9a2d26f239a31"
    end

    on_arm do
      url "https://github.com/yipjunkai/terminal-relay/releases/download/v0.1.0/terminal-relay-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "dc0e2c276fe3e0e9f5a58fb64c122b5d2d308a1a8e1ca84c63271a1ac7738e39"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yipjunkai/terminal-relay/releases/download/v0.1.0/terminal-relay-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "5a39134344ec1ec0f770b89f3d9ce0e2cd737daa409ba654103ce97bc9b4f6ad"
    end

    on_arm do
      url "https://github.com/yipjunkai/terminal-relay/releases/download/v0.1.0/terminal-relay-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "bd19b043e48ec8c74f1e2a3d7af71490324a87b2a564f595796c5d62786f5f1b"
    end
  end

  def install
    bin.install "terminal-relay"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/terminal-relay --version")
  end
end
