# Homebrew formula for terminal-relay CLI
#
# Install: brew install yipjunkai/terminal-relay/terminal-relay
#
# Maintenance:
# - This file is auto-regenerated by CI (.github/workflows/release.yml)
#   on every tag push. Version and SHA256 hashes are computed automatically.
# - The install script (install.sh) is the other install path and requires
#   no updates on release.
# - Do not edit manually — changes will be overwritten by the next release.

class TerminalRelay < Formula
  desc "Mirror local AI terminal sessions to remote clients with E2E encryption"
  homepage "https://github.com/yipjunkai/terminal-relay"
  license any_of: ["MIT", "Apache-2.0"]
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/yipjunkai/terminal-relay/releases/download/v0.2.0/terminal-relay-v0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "262e9138c7fde99bfddd22ea2aeb6fd4ce81d7095ad7a1cfe590dde8ffc0b2c0"
    end

    on_arm do
      url "https://github.com/yipjunkai/terminal-relay/releases/download/v0.2.0/terminal-relay-v0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "9f448dcaca57911cb2daba012421361a5e0a7959a686ccfd6bb2a51a71a9d1a2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yipjunkai/terminal-relay/releases/download/v0.2.0/terminal-relay-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c682744bc67f3f0d48752a871f92c554ba7e36e323b45d232648056183a02c3a"
    end

    on_arm do
      url "https://github.com/yipjunkai/terminal-relay/releases/download/v0.2.0/terminal-relay-v0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "162d462eb14f538c849fe9659e4ec3bc988cd4bbace989b8bcc6104ab4b7cb03"
    end
  end

  def install
    bin.install "terminal-relay"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/terminal-relay --version")
  end
end
