# Homebrew formula for terminal-relay CLI
#
# Install: brew install yipjunkai/terminal-relay/terminal-relay
#
# Maintenance:
# - This file is auto-regenerated by CI (.github/workflows/release.yml)
#   on every tag push. Version and SHA256 hashes are computed automatically.
# - The install script (install.sh) is the other install path and requires
#   no updates on release.
# - Do not edit manually — changes will be overwritten by the next release.

class TerminalRelay < Formula
  desc "Mirror local AI terminal sessions to remote clients with E2E encryption"
  homepage "https://github.com/yipjunkai/terminal-relay"
  license any_of: ["MIT", "Apache-2.0"]
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/yipjunkai/terminal-relay/releases/download/v#{version}/terminal-relay-v#{version}-x86_64-apple-darwin.tar.gz"
      # sha256 populated by CI after first release
    end

    on_arm do
      url "https://github.com/yipjunkai/terminal-relay/releases/download/v#{version}/terminal-relay-v#{version}-aarch64-apple-darwin.tar.gz"
      # sha256 populated by CI after first release
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yipjunkai/terminal-relay/releases/download/v#{version}/terminal-relay-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      # sha256 populated by CI after first release
    end

    on_arm do
      url "https://github.com/yipjunkai/terminal-relay/releases/download/v#{version}/terminal-relay-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      # sha256 populated by CI after first release
    end
  end

  def install
    bin.install "terminal-relay"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/terminal-relay --version")
  end
end
